### ISSUE TITLE
add the ability to change parameters for running wallfade

### ISSUE THREAD

**Issue by FredrikHson** [c0r73x/wallfade#5]
calling wallfade a second time should allow you to change the currently running instances options or just say skip the countdown and change now

**Comment by c0r73x** [comment]
Basic IPC support added in https://github.com/c0r73x/wallfade/commit/20f18fd6bb5b18c095e44a989fc361dbbb68a62d need to add more types of messages and write some help :P

**Comment by c0r73x** [comment]
Added in https://github.com/c0r73x/wallfade/commit/20f18fd6bb5b18c095e44a989fc361dbbb68a62d + https://github.com/c0r73x/wallfade/commit/7cd75ea0dd2d3c0c1ea5e49e67a7eaeb1f36185d
